# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindows.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(834, 587)
        MainWindow.setMinimumSize(QtCore.QSize(834, 587))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 834, 24))
        self.menubar.setObjectName("menubar")
        self.menuGraphes = QtWidgets.QMenu(self.menubar)
        self.menuGraphes.setObjectName("menuGraphes")
        self.menuAnalyse = QtWidgets.QMenu(self.menubar)
        self.menuAnalyse.setObjectName("menuAnalyse")
        MainWindow.setMenuBar(self.menubar)
        self.actionClients = QtWidgets.QAction(MainWindow)
        self.actionClients.setObjectName("actionClients")
        self.actionRelations = QtWidgets.QAction(MainWindow)
        self.actionRelations.setObjectName("actionRelations")
        self.actionAchats = QtWidgets.QAction(MainWindow)
        self.actionAchats.setObjectName("actionAchats")
        self.actionCommissions = QtWidgets.QAction(MainWindow)
        self.actionCommissions.setObjectName("actionCommissions")
        self.actionGraphe = QtWidgets.QAction(MainWindow)
        self.actionGraphe.setObjectName("actionGraphe")
        self.actionAcceuil = QtWidgets.QAction(MainWindow)
        self.actionAcceuil.setObjectName("actionAcceuil")
        self.menuGraphes.addAction(self.actionClients)
        self.menuGraphes.addSeparator()
        self.menuGraphes.addAction(self.actionRelations)
        self.menuGraphes.addAction(self.actionAchats)
        self.menuGraphes.addSeparator()
        self.menuGraphes.addAction(self.actionAcceuil)
        self.menuAnalyse.addAction(self.actionGraphe)
        self.menubar.addAction(self.menuGraphes.menuAction())
        self.menubar.addAction(self.menuAnalyse.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuGraphes.setTitle(_translate("MainWindow", "Gestion"))
        self.menuAnalyse.setTitle(_translate("MainWindow", "Analyse"))
        self.actionClients.setText(_translate("MainWindow", "Acceuils"))
        self.actionRelations.setText(_translate("MainWindow", "Clients"))
        self.actionAchats.setText(_translate("MainWindow", "Relations"))
        self.actionCommissions.setText(_translate("MainWindow", "Commissions"))
        self.actionGraphe.setText(_translate("MainWindow", "Graphe du reseau"))
        self.actionAcceuil.setText(_translate("MainWindow", "Achats"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
